# Generated by Django 5.1.4 on 2025-10-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_tracking', '0002_alter_jobadvert_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='decision_seen',
            field=models.BooleanField(default=False),
        ),
    ]
